@echo off
echo 启动开发服务器...
echo 启动后端开发服务器 (端口: 15001)...
start "Backend Server" /D "../backend" pnpm dev
echo 启动前端开发服务器 (端口: 15000)...
start "Frontend Server" /D "../frontend" pnpm dev
echo 开发服务器启动命令已执行，请稍候...
echo.
echo 访问地址:
echo  - 前端: http://localhost:15000
echo  - 后端API: http://localhost:15001
echo  - 网络访问前端: http://[你的IP]:15000
