// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/welcome","name":"欢迎","icon":"smile","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/auth","layout":false,"id":"3"},"4":{"path":"/auth/login","parentId":"3","id":"4"},"5":{"path":"/auth/register","parentId":"3","id":"5"},"6":{"path":"","name":"仪表盘","icon":"DashboardOutlined","parentId":"7","id":"6","originPath":"/dashboard"},"7":{"path":"/dashboard","isWrapper":true,"parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/system","name":"系统管理","icon":"SettingOutlined","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"","name":"用户管理","parentId":"10","id":"9","originPath":"/system/users"},"10":{"path":"/system/users","isWrapper":true,"parentId":"8","id":"10"},"11":{"path":"","name":"角色管理","parentId":"12","id":"11","originPath":"/system/roles"},"12":{"path":"/system/roles","isWrapper":true,"parentId":"8","id":"12"},"13":{"path":"","name":"权限管理","parentId":"14","id":"13","originPath":"/system/permissions"},"14":{"path":"/system/permissions","isWrapper":true,"parentId":"8","id":"14"},"15":{"path":"/admin","name":"管理页","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"15"},"16":{"path":"","name":"分页一","icon":"smile","parentId":"17","id":"16","originPath":"/admin/sub-page-1"},"17":{"path":"/admin/sub-page-1","isWrapper":true,"parentId":"15","id":"17"},"18":{"path":"","name":"分页二","icon":"smile","parentId":"19","id":"18","originPath":"/admin/sub-page-2"},"19":{"path":"/admin/sub-page-2","isWrapper":true,"parentId":"15","id":"19"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__AuthLayout__index" */'@/layouts/AuthLayout/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Auth__Login" */'@/pages/Auth/Login.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Auth__Register" */'@/pages/Auth/Register.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Dashboard" */'@/pages/Dashboard.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "wrappers__AuthWrapper" */'@/wrappers/AuthWrapper.tsx')),
'8': React.lazy(() => import('./EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__System__User" */'@/pages/System/User.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "wrappers__AuthWrapper" */'@/wrappers/AuthWrapper.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__System__Role" */'@/pages/System/Role.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "wrappers__AuthWrapper" */'@/wrappers/AuthWrapper.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__System__Permission" */'@/pages/System/Permission.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "wrappers__AuthWrapper" */'@/wrappers/AuthWrapper.tsx')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "wrappers__AuthWrapper" */'@/wrappers/AuthWrapper.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'19': React.lazy(() => import(/* webpackChunkName: "wrappers__AuthWrapper" */'@/wrappers/AuthWrapper.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'E:/YSY/UG/frontend/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
