// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'E:/YSY/UG/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from 'E:/YSY/UG/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SettingOutlined from 'E:/YSY/UG/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import CrownOutlined from 'E:/YSY/UG/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { SmileOutlined, DashboardOutlined, SettingOutlined, CrownOutlined };
